### ISSUE TITLE
Could I use this on server by "return result"?

### ISSUE THREAD

**Issue by thearabbit** [Didericis/callpromise-mixin#2]
I could use this on `server` by `return result`

``` js
// Server
let result = testMethod.callPromise({
    val: 'hi'
}).then(function(result){
    return result
}).catch(function(err){
    console.log(err);
});
```

**Comment by Didericis** [comment]
No, the way promises work would not allow you to populate the `result` variable you have defined on line 1 from the `return result` you have on line 4.

That being said, depending on what you're doing in the method, because you're on the server you probably don't need to use `testMethod.callPromise` and can instead just call `testMethod.run`. This will return a result immediately and allow you to write something like

``` js
let rest = testMethod.run({val: 'hi'});
```

**Comment by thearabbit** [comment]
Hi @Didericis,
Server call `testMethod.run({})` don't check validate schema
```js
// Method
export const testMethod = new ValidatedMethod({
  name: 'testMethod',
  mixins: [CallPromiseMixin],
  validate: new SimpleSchema({
    name: {
      type: String,
    },
  }).validator(),
  run({ name }) {
    if (Meteor.isServer) {
      return ........
    }
  },
})

---------
// Server
let rest = testMethod.run({}); // Still work
```
